version: '3.3'
services:
  backend:
    build:
        context: backend
        dockerfile: Dockerfile
    restart: always
    container_name: backend
    user: "${UID}:${GID}"
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - ./backend:/backend
    ports:
      - "5000:5000"
    env_file:
        - config.env
    environment:
      FLASK_APP: /backend/app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
      API_KEY: ${API_KEY}
      SQLALCHEMY_DATABASE_URI: 'postgresql://tester:complicatedpass@postgresql:5432/messages'

  postgresql:
    image: postgres:11.2
    user: "${UID}:${GID}"
    restart: always
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: complicatedpass
    ports:
      - "5432:5432"
    volumes:
      - ./docker_data/postgresql:/var/lib/postgresql/data

  nginx:
      container_name: nginx
      restart: always
      build:
          context: nginx
          dockerfile: Dockerfile
      volumes:
          - './nginx/nginx.conf:/etc/nginx/nginx.conf'
          - './frontend/dist:/var/www/dist'
      ports:
          - "80:80"
